env:
  node: true
  browser: false
  commonjs: true
  es6: true
extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - import
rules:
  prettier/prettier: error
  "no-use-before-define": 0
  "@typescript-eslint/indent": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: none
      ignoreRestSiblings: false
  class-methods-use-this: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: error
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
      groups:
        - - builtin
          - external
        - - parent
          - internal
          - sibling
        - index
        - unknown
  jest/prefer-expect-assertions: 0
  jest/prefer-strict-equal: 0
  no-console: ['error']
  no-unused-vars: 0
  no-useless-constructor: 0
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
      - ".tsx"
  import/resolver:
    typescript:
      alwaysTryTypes: true
